title: Extended Reality Flight Simulation and Control Laboratory
logo: /assets/img/profile.jpg
description: This laboratory merges Virtual and Augmented Reality (VR/AR) with full-body haptics suits and motion-base platforms to allow for immersive extended-reality (XR) simulations of aerospace vehicles. 
show_downloads: true
google_analytics: false
theme: jekyll-theme-minimal
